version: '3.9'
services:
  postgres:
    image: postgres:16-alpine3.22
    container_name: file_demo
    restart: unless-stopped
    environment:
      POSTGRES_DB: file_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGTZ: 'Europe/Kyiv'
      TZ: 'Europe/Kyiv'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
